### ISSUE TITLE
Tests

### ISSUE THREAD

**Issue by rivenblades** [fusion2004/cop4610#1]
Hey i have a similar exrcise to do. i did my implementation but when i run my tests i dont get what you get to prove my point.I mean i have a test that reads a big file and writes it but the sequence is always in the right order when it adds.
e.g add R 71
     add R 100
     add R 150
     add R 201
so it dispatches correct.
but i want it to show for e.g

     add R 100
     add R 71
     add R 150
     add R 201
and then 
     dsp R 71
    dsp R 100 ...
Can you provide me your tests files to see if im doing something wrong?

**Comment by fusion2004** [comment]
Huh, not sure why I never replied to this. This was for a class I took in 2011, and even back in 2018 I'm sure I didn't have any other files or notes for this anymore other than what you see in the repo.

Additionally, I have not written any C code since I took that class, so I would not be a good person to ask for help nowadays.

Sorry I couldn't have been more help!

**Comment by rivenblades** [comment]
It's ok.
